leftnav:
- identifier: a3434c1e-0788-7c70-7e27-9709f50545d7
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 0a931863-ac49-b685-d020-524957d0c9d7
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 8e504643-56d1-41dd-973b-0135ff136115
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1a628608-7450-ccaf-1cdb-4fdab72b880d
  name: Video Lectures
  pageRef: /video_galleries/video-lectures
  weight: 40
- identifier: a0770509-26c7-f149-64cd-95d8c8815bac
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
